-- day07 jdbc 연습
-- 학생테이블, 수강테이블

SELECT * FROM TBL_STUDENT;
SELECT * FROM TBL_ATTENDANCE;

DROP TABLE TBL_STUDENT;


CREATE TABLE TBL_STUDENT (
	STU_NUMBER NUMBER,
	STU_NAME VARCHAR2(20) NOT NULL,
	STU_MAJOR VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NUMBER)
);
	
CREATE TABLE TBL_ATTENDANCE (
	ATT_NUMBER NUMBER,
	STU_NUMBER NUMBER NOT NULL,
	ATT_DATE DATE NOT NULL,
	ATT_STATUS VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_ATTENDANCE PRIMARY KEY(ATT_NUMBER),
	CONSTRAINT FK_STU FOREIGN KEY(STU_NUMBER) REFERENCES TBL_STUDENT(STU_NUMBER)

);
	