-- 3번 : 서브쿼리

-- 1) 비연관 서브쿼리
-- 최대 급여를 받는 직원 조회
-- SELECT MAX(SALARY), FIRST_NAME
-- FROM EMPLOYEES; -- 조회하려는 행의 개수가 달라서 오류 발생

SELECT MAX(SALARY)
FROM EMPLOYEES;	-- 1행

SELECT FIRST_NAME
FROM EMPLOYEES;	-- 107행

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- 2) 연관서브쿼리 (상관서브쿼리)
-- 각 직원의 급여가 부서별 평균 급여보다 높은 직원 조회

-- (1) 부서별 평균 급여	-- 12행
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- (2) 각 직원의 급여 조회	-- 38행
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID
FROM EMPLOYEES;

-- ★☆★☆★
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID
FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY)
				FROM EMPLOYEES E2
				WHERE E.DEPARTMENT_ID  = E2.DEPARTMENT_ID
				GROUP BY DEPARTMENT_ID)			-- ★☆★☆★
				
-- 3) 단일행 서브쿼리(서브쿼리의 결과가 한 개)
-- 가장 오래된 입사일을 가진 직원의 사원번호, 이름, 입사일 조회
SELECT * FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;

-- (1) 가장 오래된 입사일 조회
SELECT MIN(HIRE_DATE)
FROM EMPLOYEES;

-- (2) 서브쿼리
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEES);

-- 4) 다중행 서브쿼리(서브쿼리의 결과가 여러 행을 반환)
-- 특정 부서에 속한 직원번호, 이름, 부서번호 조회

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID 부서
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
						FROM DEPARTMENTS
						WHERE DEPARTMENT_ID = 60);

-- 부서명까지 같이 조회한다 => JOIN을 이용하거나 서브쿼리를 2번 써야한다
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

SELECT e.employee_id, e.first_name, e.department_id, d.department_name
FROM EMPLOYEES e JOIN DEPARTMENTS d 
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
	WHERE D.DEPARTMENT_ID = 60;


SELECT
   E.EMPLOYEE_ID,
   E.FIRST_NAME,
   E.DEPARTMENT_ID, 
   (
   SELECT
      D.DEPARTMENT_NAME
   FROM
      DEPARTMENTS d
   WHERE
      D.DEPARTMENT_ID = E.DEPARTMENT_ID) AS 부서명
FROM
   EMPLOYEES e
WHERE
   E.DEPARTMENT_ID IN (
   SELECT
      DEPARTMENT_ID 
   FROM DEPARTMENTS
   WHERE DEPARTMENT_ID = 60);


-- PLAYER 테이블 조회
SELECT * FROM PLAYER ;										

-- 전체 평균키 포지션별 평균키
--메인쿼리 행의 수 > 서브쿼리 행의 수  O
--메인쿼리 행의 수 < 서브쿼리 행의 수  X
--그룹으로 묶은 행의 수보다 적은행을 같이 조회하는 것 가능하다

--SELECT "POSITION", AVG(HEIGTH), (SELECT * FROM PLAYER)
--FROM PLAYER
--WHERE "POSITION" IS NOT NULL
--GROUP BY "POSITION";

--SELECT "POSITION", AVG(HEIGHT), (SELECT * FROM PLAYER)
--FROM PLAYER
--WHERE "POSITION" IS NOT NULL
--GROUP BY "POSITION";

--							↓
							
SELECT "POSITION", AVG(HEIGHT) "그룹별 평균 키", (SELECT AVG(HEIGHT) FROM PLAYER) "전체 평균키"
FROM PLAYER
WHERE "POSITION" IS NOT NULL
GROUP BY "POSITION";

-- SELECT 한 결과에서 SELECT하는 서브쿼리
-- TEAM_ID가 K01인 선수 중에서 POSITION GK인 선수를 조회하기
SELECT * FROM PLAYER
WHERE TEAM_ID = 'K01' AND "POSITION" ='GK';

-- 서브쿼리로 연습
SELECT * FROM PLAYER p 
WHERE TEAM_ID = 'K01'; -- 45행

SELECT * FROM PLAYER p 
WHERE "POSITION" = 'GK'; -- 43행

SELECT *
FROM PLAYER p 
WHERE p.PLAYER_ID IN (
	SELECT PLAYER_ID 
	FROM PLAYER
	WHERE "POSITION" = 'GK');
AND TEAM_ID = 'K01';













